baseurl = "http://karteek.net"
languageCode = "en-us"
title = "Karteek dot Net"
theme = "liquorice"

[params]
  author = "karteek"
  description = "Home of Karteek Edamadaka. I write my thoughts about various topics here"
